title: Saritha's GitHub Site
author: Saritha
email: saritha.vrittamani@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  New GitHub Site
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
