title: Saritha's GitHub Site
author: Saritha
email: savritta@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
Saritha's First GitHub Site

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
